### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'updateToken')

### ISSUE THREAD

**Issue by aryo** [twilio/twilio-conversations-demo-react#152]
We're following the [example](https://github.com/twilio/twilio-conversations-demo-react/blob/main/src/components/AppContainer.tsx#L237), where on `tokenAboutToExpire` we fetch a new token and call `client.updateToken`, but we're seeing a lot of these errors:

```
TypeError: Cannot read properties of undefined (reading 'updateToken')
  at call(node_modules/@twilio/conversations/builds/browser.js:9351:49)
  at tryCatch(node_modules/@twilio/conversations/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
  at _invoke(node_modules/@twilio/conversations/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
  at key(node_modules/@twilio/conversations/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
  at asyncGeneratorStep(node_modules/@twilio/conversations/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:20)
  at _next(node_modules/@twilio/conversations/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
```

We are thinking of try/catching `client.updateToken` so it doesn't die, but from reading the conversations js internals, it looks like internally `Client._fpaToken` won't get set due to the error. Would there be any bad side effects?

We're on @twilio/conversations 2.4.1.

**Comment by berkus** [comment]
This means your client is undefined. Probably not yet initialized.

**Comment by aryo** [comment]
@berkus the client is defined. the error is thrown internally from within Client:

![image](https://github.com/twilio/twilio-conversations-demo-react/assets/380114/3ac1ab0c-52fb-4a9f-8089-feb343198abd)

**Comment by berkus** [comment]
@kmorope pls take a look at this folks.

**Comment by kmorope** [comment]
Hi @aryo, I'm trying to replicate the scenario for the issue but gonna need further info on your tech stack, are you using CRA like the Twilio conversations demo app or another framework? I made some tests directly on the demo app changing the token TTL, but the client is always defined, even in cases where the TTL is defined in less than a minute.

**Comment by aryo** [comment]
@kmorope Sorry for late reply, but yeah we are using CRA and the client instance lifecycle is similar to the example. A slight difference is that we have more things that can trigger another deinitialization of the client (e.g. log out etc) and we shutdown the client after removing listeners:
```
client.removeAllListeners();
await client.shutdown();
```

For completeness here's our initialization sequence + `tokenAboutToExpire` registration:
```
const token = await getToken();
const client = new Client(token)

client.on("tokenAboutToExpire", async () => {
  const token = await getToken();
  await client.updateToken(token);
});
```

**Comment by agrukhal** [comment]
Hi @aryo ! With the newest SDK versions (2.6.3 - latest), is the issue still present?

**Comment by agrukhal** [comment]
if it still is: 
Does it happen before you have tried to shutdown the client and remove all listeners?
And when you shutdown the client, do you recreate all the listeners again (seeing as you have removed them during those steps) ?

**Comment by aryo** [comment]
Hi @agrukhal, sorry it's been a while. 

We've upgraded to 2.6.0 a while back and it is still happening albeit very rarely. We do recreate all the listeners again everytime we reinitialize the client.

We ended up parking the issue since it was affecting a small percentage of our users, but we had some thoughts for further investigation:

- Quite a lot of the errors are happening within an hour of a suspend/resume cycle.
- On system suspend, we remove all listeners and shutdown the client
- On system resume, we reinitialize the client, which should be using a fresh access token, so why is it expiring so soon and triggering a `tokenWillExpire`?

We have a suspicion that cleaning up off the back the system suspend isn't completing properly. What is the recommendation on client cleanup in system power suspend/resume scenarios?

**Comment by agrukhal** [comment]
Hi @aryo ! Thanks for your reply. Sorry for taking so long to respond as well!
One question - are you waiting for your client to be initialized before you start using it? 
I am talking about the `connectionsStateChanged` event, line 80 like here: 
https://www.twilio.com/docs/conversations/javascript/exploring-conversations-javascript-quickstart#initializing-the-conversations-client . The client is only ready to be called after `connected` event is received

**Comment by agrukhal** [comment]
Hi again! We were not able to reproduce this, so the investigation was not fruitful. If this issue still persists, can you, please, provide more logs with setting the loglevel to _trace_ like so: `const client = new Client("token", { logLevel: "trace" })`

I will close this issue for now. Please, open/reopen if there is any follow-up needed
